export const constants = {
    ACCESS_TOKEN_KEY: "ACCESS TOKEN KEY",
    STORAGE_KEY: "[Backlog] STORAGE KEY",
    TENANT_KEY: "TENANT KEY",
    LOGIN_CREDENTIALS_KEY: "LOGIN CREDENTIALS KEY",
    BASE_URL: "BASE URL",
    CURRENT_USER_KEY: "CURRENT_USER_KEY",
    DEFAULT_PATH: "DEFAULT_PATH"
};